<?php

use Illuminate\Database\Seeder;

class ArticulosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $productos=array('Acoples','Mini Plug y RCA','Alicates  para  RJ - 45','Antenas de  TV  a  Control',
        'Cables  UCB',
        'Cable   de  corriente  de  Poder',
        'Cable  de  Audio',
        'Cable   de  Microfono  de  100LL.',
        'Cables  Coaxiales   de  300LL',
        'Cables  UTP  CAT-5',
        'Capacitores  Ceramicos',
        'Capacitores  Poliester',
        'Cautin  para  Soldar',
        'Cautin P/ de  Plata',
        'Circuitos  Integrados STK',
        'Circuitos  Integrados STR',
        'Circuitos  Integrados  CMOS',
        'Circuitos  Integrados',
        'Conos  de  Parlantes',
        'Controles  para  TV',
        'Cortapicos',
        'Desarmadores  en  juegos',
        'Displeys  Anodo y Catodo',
        'Diodos  Rectificadores',
        'Diodo  De  Alta',
        'Diodos  en  puentes',
        'Diodo  Zener de 1W',
        'Diodo  Zener de  1/2 W',
        'Draiver de  300w',
        'Engranajes de  radios',
        'Fajas  de  DVD',
        'Filtros   Pequeños ',  
        'Filtros   Pequeños   Bipolar',
        'Filtros   Medianos',
        'Filtros   Regulares',
        'Filtros  Grandes',
        'Filtros  Extragrandes',
        'Foquitos Led',
        'Foquitos  de  12V',
        'Fusibles  Pequeños y Grandes',
        'Flayback',
        'Hilo  Dial  de  100LL',
        'Lectores de  CD - DVD - VCD',
        'Lectores de  Playsteciön',
        'Laminas de  Cobre',
        'Mangueras  de  Luces',
        'Microfonos',
        'Moduladores  RF',
        'Motores  de  Radio',
        'Motores  de  DVD',
        'Minitaladros',
        'Poleas',
        'Potenciometros',
        'Potenciometros  Minis',
        'Potenciometros  de  TV',
        'Plug  Metalicos',
        'Plug  Conon',
        'Placas  Perforadas',
        'Parlantes  Pequeños',
        'Parlantes  Medianos',
        'Parlantes',
        'Parlantes  Grandes',
        'Pistolas',
        'Perclorato Ferrico',
        'Relay  de  12V',
        'Relay  de  24V',
        'Resistencias  de 5W',
        'Resistencias  de 10W',
        'Resistencias  de 2W',
        'Resistencias  de  3W',
        'Resistencias  de  1/4W',
        'Resistencias de  1/2W',
        'Socalos  de  TV',
        'Socalos  de Circuitos  Integrados',
        'Sintonizador  para  TV',
        'Spliters  Chino',
        'Spliters  Americanos',
        'Tapas  de  Parlantes',
        'Transistores  Horizontales',
        'Transistores  Tipo  TIP',
        'Transistores  Tipo  BC',
        'Transistores  Tipo Platillo',
        'Tester  Digital' ,
        'Tester  Analogico',
        'Thuiters',
        'Thuiters  Original',
        'Transformadores',
        'Transformadores  Grandes',
        'Ventiladores de  12V',
        'Ventiladores de 220V',
        'Alambre de cobre del # 13 al # 29',
        'Alambre de cobre del # 30 al # 43',
        'Barnis para transformadores',
        'Material Electrico para transformador');
        for($i=0;$i<94;$i++){
            DB::table('articulos')->insert([
                'idcategoria'=>rand(1,6),
                'idunidad'=>rand(1,3),
                'idmarca'=>rand(1,6),
                'codigo'=>'A00'.rand(0,50),
                'nombre' =>$productos[$i],
                'image' => $i.'.jpg',
                'precio'=>rand(20,9000),
                'stock'=>rand(1,50),
                'descripcion'=>'Articulos de '.$productos[$i],
                'created_at'=>now(),
                'updated_at'=>now(),
               ]);
        }
    }
}
